apiVersion: apps/v1 
kind: Deployment
metadata:
  name: deploy-concert
spec:
  selector:  
    matchLabels:
      app: concertapp
  replicas: 2
  template:  
    spec:
      containers:
      - name: concertapp
        image: dnazarenocr.azurecr.io/concert-app:1.0
        resources:
          limits:
              memory: "300Mi"
              cpu: "300m"
          requests:
              memory: "200Mi" 
              cpu: "200m"
        livenessProbe:
          exec:
            command:
            - ls
            - /tmp/
          initialDelaySeconds: 2
          periodSeconds: 2
        ports:
        - containerPort: 80
        env:
          - name: DB_DATABASE_HOST
            valueFrom:
              configMapKeyRef:
                name: datos-concert
                key: DB_DATABASE_HOST
          - name: DB_DATABASE_USER
            valueFrom:
              configMapKeyRef:
                name: datos-concert
                key: DB_DATABASE_USER
          - name: DB_DATABASE
            valueFrom:
              configMapKeyRef:
                name: datos-concert
                key: DB_DATABASE
          - name: DB_DATABASE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: secretos-concert
                key: DB_DATABASE_PASSWORD
      imagePullSecrets:
      - name: regcred

