apiVersion: apps/v1 
kind: Deployment
metadata:
  name: deploy-concert
spec:
  selector:  
    matchLabels:
      app: concertapp
  template:   
    metadata:
      labels:
        app: concertapp
  replicas: 2
  # strategy:
  #    type: Recreate
  containers:
    - name: concertapp
      ports:
      - containerPort: 8081
      image: crdnazareno.azurecr.io/concert-app
      resources:
        limits:
            memory: "200Mi"
            cpu: "2"
        requests:
            memory: "100Mi" 
            cpu: "0.5"
  imagePullSecrets:
    - name: regcred
