
labels:
- includeSelectors: false
  pairs:
    entorno: dev
nameSuffix: -dev
patches:
- target:
    kind: Ingress
    name: ingress-weekly
    group: networking.k8s.io
    version: v1
  path: kustomize-patches/ingress-patches-dev.yaml
