
labels:
- includeSelectors: false
  pairs:
    entorno: dev
    app: concertapp-dev
nameSuffix: -dev

patches:
- target:
    kind: Ingress
    name: ingress-weekly
    group: networking.k8s.io
    version: v1
  path: kustomize-patches/ingress-patch-dev.yaml
- target:
    kind: Service
    name: service-concert
  path: kustomize-patches/service-concert-patch-dev.yaml
- target:
    kind: Service
    name: service-phpmyadmin
  path: kustomize-patches/service-db-patch-dev.yaml
- target:
    kind: Deployment
    name: deploy-concert
  path: kustomize-patches/deploy-concert-patch-dev.yaml
- target:
    kind: Deployment
    name: deploy-phpmyadmin
  path: kustomize-patches/deploy-db-patch-dev.yaml

configMapGenerator:
- name: datos-concert
  behavior: merge
  literals:
  - DB_DATABASE=concierto_dev
