
labels:
- includeSelectors: false
  pairs:
    entorno: dev
nameSuffix: -dev
patches:
- target:
    kind: Ingress
    name: ingress-weekly
    group: networking.k8s.io
    version: v1
  path: kustomize-patches/ingress-patches-dev.yaml
- target:
    kind: Service
    name: service-concert
  path: kustomize-patches/services-patches-dev.yaml
- target:
    kind: Service
    name: service-phpmyadmin
  path: kustomize-patches/services-patches-dev.yaml
