apiVersion: v1
kind: Service
metadata:
  name: service-concert
  namespace: ns_dnazareno
  labels:
     app: concertapp
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
     app: concertapp
