apiVersion: v1
kind: Service
metadata:
  name: service-phpmyadmin
  namespace: ns-dnazareno
  labels:
     app: phpmyadmin
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
     app: phpmyadmin
