name: 'Start Ansible'
description: 'Configure a VM to execute playbooks and more'
inputs:
  PRIVATE_IP_VMDB:  
    required: true
    type: string
  VM1_PASS:  
    required: true
    type: string
  VM1_USER:  
    required: true
    type: string
runs:
  using: "composite"
  steps:
    - name: Deploying ansible on vm backup
      shell: bash
      run: |
        ssh-keygen -t rsa -N "" -f ~/.ssh/id_rsa
        sudo apt update
        sudo apt -y install sshpass
        sudo apt -y install mysql-client-core-8.0
        sudo apt -y install mysql-server
        sudo apt -y install ansible
        curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
        ssh-keyscan -H ${{ inputs.PRIVATE_IP_VMDB }} >> ~/.ssh/known_hosts
        sshpass -p "${{ inputs.VM1_PASS }}" ssh-copy-id ${{ inputs.VM1_USER }}@${{ inputs.PRIVATE_IP_VMDB }}
      # env:
      #   INPUT_PRIVATE_IP_VMDB: ${{ inputs.PRIVATE_IP_VMDB }}
      #   INPUT_VM1_PASS: ${{ inputs.VM1_PASS }}
      #   INPUT_VM1_USER: ${{ inputs.VM1_USER }}
