name: 'Ansible'

on:  workflow_dispatch
  # push:
  #   branches: [main]
    
jobs:
  ansible:
    name: 'Ansible'
    runs-on: self-hosted
 
    defaults:
      run:
        shell: bash
 
    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v4
         
    - name: Deploy
      run: |
        ansible-playbook -i Ansible/inventario Ansible/database_playbook.yaml --vault-password-file Ansible/pass.yaml
