name: CICD Checks
on:
  workflow_call:
      
jobs:
  CICDchecks:
    name: CICD Checks
    runs-on: ubuntu-latest
    # Map the job outputs to step outputs
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Pruebas unitarias
        run: echo "Tests unitarios superados con éxito"

      - name: Pruebas de integracion
        run: echo "Tests de integración superados con éxito"

      - name: Pruebas End to End
        run: echo "Tests End to End superados con éxito"
