name: CI APP
on:
  workflow_dispatch:
  pull_request:
    types: [opened,reopened]
    branches: 
      - 'main'
    paths:
      - 'concert-app/**'
      - 'K8s/**'
jobs:
  build:
    runs-on: ubuntu-latest

    outputs:
      tag: ${{ steps.get_version.outputs.version }} #tag será un output

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Pruebas unitarias
        run: echo "Tests unitarios superados con éxito"

      - name: Pruebas de integracion
        run: echo "Tests de integración superados con éxito"

      - name: Pruebas End to End
        run: echo "Tests End to End superados con éxito"

      - name: Run markdown lint
        run: |
          npm install remark-cli remark-preset-lint-consistent vfile-reporter-json
          npx remark . --use remark-preset-lint-consistent --report vfile-reporter-json 2> remark-lint-report.json

      - uses: actions/upload-artifact@v3
        with:
          name: remark-lint-report
          path: remark-lint-report.json
          
      - name: Get version from package.json
        id: get_version
        run: | 
          echo "version=$(jq -r .version concert-app/composer.json)" >> "$GITHUB_OUTPUT"
          echo $GITHUB_OUTPUT
          

