name: CI APP
on:
  pull_request:
    types: [opened,reopened]
    branches: 
      - 'main'
    paths:
      - 'concert-app/**'
      - 'K8s/**'
jobs:     
  build:
    runs-on: ubuntu-latest

    outputs:
      nombre: ${{ steps.get_version.outputs.version }}
      tag: ${{ steps.get_version.outputs.version }} #tag será un output
      
    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Get version from package.json
        id: get_version
        run: | 
          echo "name=$(jq -r name composer.json)" >> "$GITHUB_OUTPUT"
          echo "version=$(jq -r version composer.json)" >> "$GITHUB_OUTPUT"
          echo $GITHUB_OUTPUT
          
  call-reusable-workflow:
    uses: ./.github/workflows/dockerizacion_workflow.yaml
    with:
      image-to-build: ${{ needs.build.outputs.nombre }}:${{ needs.build.outputs.tag }}
    secrets: inherit
