name: CICD APP DEV
on: # [workflow_dispatch,workflow_call]
   workflow_dispatch:
   push:
     branches: 
       - 'dnazareno'
     paths:
       - 'concert-app/controller/**'
       - 'concert-app/model/**'
       - 'concert-app/view/**'
       - 'concert-app/Dockerfile'
       - 'concert-app/index.php'
       - 'K8s/**'
jobs:
  get_version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get Version
        id: get_version
        uses: ./.github/actions/get-version
        with:
            entorno: dev

  call-reusable-ci-workflow:
    needs: get_version
    uses: ./.github/workflows/dockerizacion_workflow.yaml
    with:
      tag: ${{ needs.get_version.outputs.tag }}
      entorno: dev
    secrets: inherit

  CD-test:
    needs: [get_version,call-reusable-ci-workflow]
    uses: ./.github/workflows/k8s_kustomize_workflow.yaml
    with:
      tag: ${{ needs.get_version.outputs.tag }}
      entorno: dev
    secrets: inherit
          
          
