name: CICD APP PROD
on: # [workflow_dispatch,workflow_call]
   workflow_dispatch:
   push:
     branches: 
       - 'main'
     paths:
       - 'concert-app/controller/**'
       - 'concert-app/model/**'
       - 'concert-app/view/**'
       - 'concert-app/Dockerfile'
       - 'concert-app/index.php'
       - 'K8s/**'
jobs:
  get_version:
    uses: ./.github/workflows/get_version_workflow.yaml

  call-reusable-ci-workflow:
    needs: get_version
    uses: ./.github/workflows/dockerizacion_workflow.yaml
    with:
      tag: ${{ needs.get_version.outputs.tag }}
      entorno: prod
    secrets: inherit

  CD-test:
    needs: [get_version,call-reusable-ci-workflow]
    uses: ./.github/workflows/k8s_kustomize_workflow.yaml
    with:
      tag: ${{ needs.get_version.outputs.tag }}
      entorno: prod
    secrets: inherit
          
          
