name: CICD APP PROD
on: # [workflow_dispatch,workflow_call]
   workflow_dispatch:
   push:
     branches: 
       - 'main'
     paths:
       - 'concert-app/controller/**'
       - 'concert-app/model/**'
       - 'concert-app/view/**'
       - 'concert-app/Dockerfile'
       - 'concert-app/index.php'
       - 'K8s/**'
jobs:
  call-reusable-checks-workflow:
    uses: ./.github/workflows/checks.yaml
    
  get_version:
    needs: call-reusable-checks-workflow
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.get_version.outputs.tag }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get Version
        id: get_version
        uses: ./.github/actions/get-version
        with:
            entorno: production

  call-reusable-ci-workflow:
   needs: [call-reusable-checks-workflow,get_version]
   uses: ./.github/workflows/dockerizacion_workflow.yaml
   with:
      tag: ${{ needs.get_version.outputs.tag }}
      entorno: production
   secrets: inherit

  CD-test:
    needs: [call-reusable-checks-workflow,get_version,call-reusable-ci-workflow]
    uses: ./.github/workflows/k8s_kustomize_workflow.yaml
    with:
      tag: ${{ needs.get_version.outputs.tag }}
      entorno: production
    secrets: inherit
          
  call-reusable-updater-workflow:
     needs: [call-reusable-checks-workflow,get_version,call-reusable-ci-workflow,CD-test]
     uses: ./.github/workflows/update_composer_workflow.yaml
     permissions:
      contents: write
