name: 'DB Backup'

on:  workflow_dispatch
  # push:
  #   branches: [main]
    
jobs:
  backup:
    name: 'DB Backup'
    runs-on: self-hosted
    defaults:
      run:
        shell: bash

    steps:
    - uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        
    - name: Backup
      run: |
        namedate=$(date +'%Y%m%d%H%M%S')
        mysqldump -h ${{ vars.DB_HOST }} -u ${{ vars.DB_USER }} -p${{ secrets.DB_PASSWORD }} ${{ vars.DB_NAME }} > backup.sql
        tar -czvf backup.tar.gz backup.sql
        az storage blob upload --account-name stadnazarenodvfinlab --container-name dbbackup --name backup.tar.gz --file backup.tar.gz --auth-mode login

