name: 'DB Restore'

on:  
    workflow_dispatch:
        inputs:
          backup:
            required: true
            type: string

    
jobs:
  backup:
    name: 'DB Restore'
    runs-on: self-hosted
    defaults:
      run:
        shell: bash

    steps:
    - uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        
    - name: Restore
      run: |
        az storage blob download --account-name ${{ secrets.STA_NAME }} --container-name ${{ secrets.CONTAINER_NAME }} --name ${{ github.event.inputs.backup }}.tar.gz --file ${{ github.event.inputs.backup }}.tar.gz
        tar -xzvf ${{ github.event.inputs.backup }}.tar.gz ${{ github.event.inputs.backup }}.sql
        mysql -u ${{ vars.DB_USER }} -p${{ secrets.DB_PASSWORD }} -h ${{ vars.DB_HOST }} concierto < ${{ github.event.inputs.backup }}.sql
        
        
