name: Dockerizacion
on:
  workflow_call:
    inputs:
      tag:
        required: true
        type: string
#on:  workflow_dispatch
jobs:
  build:
    name: 'Build and Push to ACR'
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: build and push
        run: |
          docker build -t dboffelli/concert-app:${{ inputs.tag }} concert-app/.
          docker tag dboffelli/concert-app:${{ inputs.tag }}  dnazarenocr.azurecr.io/concert-app:${{ inputs.tag }}
          az acr login --name dnazarenocr
          docker push dnazarenocr.azurecr.io/concert-app:${{ inputs.tag }}
