name: Dockerizacion
on:
  workflow_call:
    inputs:
      image-to-build:
        required: true
        type: string
#on:  workflow_dispatch
jobs:
  build:
    name: 'Build and Push to ACR'
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: build and push
        run: |
          docker build -t dboffelli/${{ inputs.image-to-build }} concert-app/.
          docker tag dboffelli/${{ inputs.image-to-build }}  dnazarenocr.azurecr.io/${{ inputs.image-to-build }}
          az acr login --name dnazarenocr
          docker push dnazarenocr.azurecr.io/${{ inputs.image-to-build }}
