name: 'K8s job'
on:  workflow_dispatch
    
jobs:
  k8s:
    name: 'K8s'
    runs-on: ubuntu-latest
    environment: production
 
    defaults:
      run:
        shell: bash
 
    steps:
    - uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

            # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Connection to cluster
      run: |
        az acr login --name ${{ vars.CONTAINER_REGISTRY_NAME }}
        az account set --subscription ${{ secrets.SUBSCRIPTION_ID }}
        az aks get-credentials --resource-group ${{ vars.COMMON_RESOURCE_GROUP_NAME }} --name ${{ vars.KUBERNETES_CLUSTER_NAME }} --overwrite-existing
        curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
        /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
        (echo; echo 'eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"') >> /home/runner/.bashrc
        eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
        sudo apt-get install build-essential
        brew install Azure/kubelogin/kubelogin
        kubelogin convert-kubeconfig -l azurecli
        cd K8s/
        cat kustomize-base.yaml kustomize-dev.yaml > kustomization.yaml
        kustomize edit set image dnazarenocr.azurecr.io/concert-app=dnazarenocr.azurecr.io/concert-app:20240703082342
        kustomize build
        kustomize build > manifesttodeploy.yaml
        kubectl apply -f manifesttodeploy.yaml -n ns-dnazareno
        kubectl get all -n ns-dnazareno
