name: 'K8s Deploy dev'
on:  
  workflow_dispatch:
  workflow_call:
    inputs:
      tag:
        required: true
        type: string
      entorno:
        required: true
        type: string
    
jobs:
  k8s:
    name: 'K8s'
    runs-on: ubuntu-latest
    environment: production
 
    defaults:
      run:
        shell: bash
 
    steps:
    - uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

            # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Connection to cluster
      run: |
        az acr login --name ${{ vars.CONTAINER_REGISTRY_NAME }}${{ inputs.entorno }}
        az account set --subscription ${{ secrets.SUBSCRIPTION_ID }}
        az aks get-credentials --resource-group ${{ vars.COMMON_RESOURCE_GROUP_NAME }} --name ${{ vars.KUBERNETES_CLUSTER_NAME }} --overwrite-existing
        curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
        /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
        (echo; echo 'eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"') >> /home/runner/.bashrc
        eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
        sudo apt-get install build-essential
        brew install Azure/kubelogin/kubelogin
        kubelogin convert-kubeconfig -l azurecli
        cd K8s/
        cat kustomize-base.yaml kustomize-${{ inputs.entorno }}.yaml > kustomization.yaml
        kustomize edit set image dnazarenocr.azurecr.io/concert-app=dnazarenocr${{ inputs.entorno }}.azurecr.io/concert-app:${{ inputs.tag }}
        kustomize build
        kustomize build > manifesttodeploy.yaml
        kubectl apply -f datos-phpmyadmin.yaml -n ns-dnazareno
        kubectl apply -f secretos-concert.yaml -n ns-dnazareno
        kubectl apply -f secretos-phpmyadmin.yaml -n ns-dnazareno
        kubectl apply -f deploy-phpmyadmin.yaml -n ns-dnazareno
        kubectl apply -f service-phpmyadmin.yaml -n ns-dnazareno
        kubectl apply -f manifesttodeploy.yaml -n ns-dnazareno
        kubectl get all -n ns-dnazareno
        kubectl get service ingress-nginx-controller --namespace=ingress-nginx
