# File: .github/workflows/workflow.yml

on: workflow_dispatch

name: AzureCLISample2

jobs:

  build-and-deploy:
    runs-on: ubuntu-latest
    steps:

    - uses: azure/login@v1
      with:
         client-id: ${{ secrets.CLIENT_ID }}
         tenant-id: ${{ secrets.TENANT_ID }}
         subscription-id: ${{ secrets.SUBSCRIPTION_ID }}

    - uses: azure/aks-set-context@v3
      with:
         resource-group: 'final-project-common'
         cluster-name: 'aksbootcampwe01'
