# File: .github/workflows/workflow.yml

on: workflow_dispatch

name: AzureCLISample3

jobs:

  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    
    - uses: azure/login@v1
      with:
         creds: ${{ secrets.AZURE_CREDENTIALS }}

    - uses: azure/aks-set-context@v3
      with:
         resource-group: 'final-project-common'
         cluster-name: 'aksbootcampwe01'

    - name: Set imagePullSecret
      uses: azure/k8s-create-secret@v4
      with:
         namespace: 'ns-dnazareno'
         secret-name: 'regcred'
         container-registry-url: ${{ vars.CONTAINER_REGISTRY_SERVER }}
         container-registry-username: ${{ vars.CONTAINER_REGISTRY_USERNAME }}
         container-registry-password: ${{ secrets.CONTAINER_REGISTRY_PASSWORD }}
      id: create-secret
