# File: .github/workflows/workflow.yml

on: workflow_dispatch

name: AzureCLISample3

jobs:

  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    
    - uses: azure/login@v1
      with:
         creds: ${{ secrets.AZURE_CREDENTIALS }}

    - uses: azure/aks-set-context@v3
      with:
         resource-group: 'final-project-common'
         cluster-name: 'aksbootcampwe01'


    - name: Connection to cluster and secret create
      run: |       
        kubectl create secret docker-registry regcred --docker-server=${{ vars.CONTAINER_REGISTRY_SERVER }} --docker-username=${{ vars.CONTAINER_REGISTRY_USERNAME }} --docker-password=${{ secrets.CONTAINER_REGISTRY_PASSWORD }} -n ns-dnazareno
    
