name: 1. Show Secret Value

on:
  workflow_dispatch:
    inputs:
      secretName:
        description: 'Name of the secret to show'
        required: true

jobs:
  show-secret:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Show secret value
        uses: stemdo-labs/actions/show-secret-value@show-secret-value
        with:
          secret_value: ${{ secrets[github.event.inputs.secretName] }}
