name: 'Start Ansible composite action'

on:  workflow_dispatch
    
jobs:
  start_ansible:
    name: 'Start Ansible'
    runs-on: self-hosted
 
    defaults:
      run:
        shell: bash
 
    steps:
    - uses: actions/checkout@v4
    # - uses: stemdo-labs/composite-actions-dnazareno@main
    - uses: ./.github/actions/composite-actions-dnazareno@main
      with:
        PRIVATE_IP_VMDB: ${{ vars.PRIVATE_IP_VMDB }}
        VM1_PASS: ${{ secrets.VM1_PASS }}
        VM1_USER: ${{ vars.VM1_USER }}
