name: Start Self-hosted Runner (Unattended)
on:
  workflow_dispatch:
    inputs:
      UNATTENDED:
        type: choice
        options: 
        - "yes"
        - "no"
        default: "yes"
        description: Disable interactive prompts for missing arguments. Defaults will be used for missing options
      REPLACE:
        type: choice
        options: 
        - "yes"
        - "no"
        default: "yes"
        description: Replace any existing runner with the same name
      LINUX_USER:
        required: true
        type: string
        description: User used to access the virtual machine
      LINUX_USER_PASS:
        required: true
        type: string
        description: Password of the user used to access the virtual machine
      LINUX_IP:
        required: true
        type: string
        description: IP of the virtual machine
      REPO_URL:
        required: true
        type: string
        description: Repository to add the runner to. Required if unattended
      RUNNER_TOKEN:
        required: true
        type: string
        description: Registration token. Required if unattended
jobs:
  start-runner:
    runs-on: ubuntu-latest
    steps:
#      - name: Checkout repository
#        uses: actions/checkout@v2
      
      - name: Start Self-hosted Runner
        uses: stemdo-labs/actions/start_linux_selfhosted_runner@main
        with:
          linuxUser: "${{ github.event.inputs.LINUX_USER }}"
          linuxUserPass: "${{ github.event.inputs.LINUX_USER_PASS }}"
          linuxIP: "${{ github.event.inputs.LINUX_IP }}"
          unattended: "${{ github.event.inputs.UNATTENDED }}"
          url: "${{ github.event.inputs.REPO_URL }}"
          token: "${{ github.event.inputs.RUNNER_TOKEN }}"
          replace: "${{ github.event.inputs.REPLACE }}"
