name: 'Start test'

on:  workflow_dispatch
    
jobs:
  start_ansible:
    name: 'Start Ansible'
    runs-on: self-hosted
 
    defaults:
      run:
        shell: bash
 
    steps:
    - name: Deploying ansible on vm backup
      run: |
       ssh-keygen -t rsa -N "" -f ~/.ssh/id_rsa
       sudo apt update
       sudo apt -y install sshpass
       sudo apt -y install mysql-client-core-8.0
       sudo apt -y install mysql-server
       sudo apt -y install ansible
       curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
#       ssh-keyscan -H ${{ vars.PRIVATE_IP_VMDB }} >> ~/.ssh/known_hosts
#       sshpass -p "${{ secrets.VM1_PASS }}" ssh-copy-id ${{ vars.VM1_USER }}@${{ vars.PRIVATE_IP_VMDB }}
