name: 'Terraform Apply'

on:  workflow_dispatch
  # push:
  #   branches: [main]
    
jobs:
  terraform:
    name: 'Terraform'
    env:
      ARM_CLIENT_ID: ${{ secrets.CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.TENANT_ID }}
      TF_VERSION: 1.5.7
    runs-on: self-hosted
 
    defaults:
      run:
        shell: bash
 
    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v4
         
    - name: Deploy
      run: |
        ansible-playbook -i Ansible/inventario Ansible/database_playbook.yaml #--skip-tags initialquery,rootpassword
