name: 'Test'

on:  workflow_dispatch
    
jobs:
  start_ansible:
    name: 'Start Ansible'
    runs-on: self-hosted
 
    defaults:
      run:
        shell: bash
 
    steps:
    - uses: actions/checkout@v4
    - name: Deploying ansible on vm backup
      run: |
          ls
